apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  labels:
    type: local # why ?
    app: postgres
spec:
  storageClassName: manual # whaaat
  capacity:
    storage: 5Gi # what is that
  accessModes:
  - ReadWriteOnce # what is that for
  hostPath:
    path:  /var/lib/postgresql/data


--- # seriously what is this for ???? oh apparently signal the start of a file
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume
  labels:
    app: postgres
spec:
  storageClassName: manual # whaaat
  accessModes:
  - ReadWriteOnce # what is that for
  resources:
    requests:
      storage: 5Gi